@echo off
echo Downloading axios...
curl -L https://registry.npmjs.org/axios/-/axios-1.6.7.tgz -o axios.tgz
echo Creating axios directory...
mkdir .\node_modules\axios
echo Extracting axios...
tar -xzf axios.tgz -C .\node_modules\axios --strip-components=1
echo Cleaning up...
del axios.tgz
echo Done!