/** @type {import('tailwindcss').Config} */
export default {
  safelist: [
    'font-medium',
    'font-semibold',
    'tracking-tight',
    'leading-relaxed',
    'transition-all',
    'duration-200',
    'duration-300',
    'transition-colors',
    'transition-transform',
    'ease-in-out',
    'hover:bg-primary/80',
    'hover:bg-secondary/80',
    'hover:bg-destructive/80',
    'hover:bg-muted',
    'hover:bg-muted/50',
    'hover:bg-muted/80',
    'hover:bg-primary/90',
    'hover:bg-secondary/80',
    'hover:bg-accent',
    'hover:text-accent-foreground',
    'hover:bg-destructive/30',
    'hover:bg-success/30',
    'hover:bg-warning/30',
    'hover:bg-info/30',
    'hover:shadow-lg',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-ring',
    'focus:ring-offset-2',
    'focus:bg-accent',
    'focus:text-accent-foreground',
    'focus:bg-destructive/10',
    'focus:text-destructive',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-ring',
    'focus-visible:ring-offset-2',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'file:border-0',
    'file:bg-transparent',
    'file:text-sm',
    'file:font-medium',
    'placeholder:text-muted-foreground',
    'data-[disabled]:pointer-events-none',
    'data-[disabled]:opacity-50',
    'data-[state=selected]:bg-accent',
    'data-[state=selected]:bg-muted',
    'data-[state=selected]:text-accent-foreground',
    'animate-in',
    'fade-in-80',
    'cursor-default',
    'select-none',
    'transform',
    'lg:translate-x-0',
    'inset-y-0',
    'left-0',
    'z-50',
    'w-64',
    'fixed',
    'whitespace-nowrap',
    'align-middle',
    'text-left',
    'uppercase',
    'text-xs',
    'overflow-x-auto',
    'bg-background',
    'text-foreground',
    'border-border'
  ],
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'border-border', // Força Tailwind a gerar essa classe
    'font-medium',
    'font-semibold',
    'tracking-tight',
    'leading-relaxed',
    'transition-all',
    'duration-200',
    'duration-300',
    'transition-colors',
    'transition-transform',
    'ease-in-out',
    'hover:shadow-lg',
    'hover:bg-primary/90',
    'hover:bg-primary/80',
    'hover:bg-secondary/80',
    'hover:bg-accent',
    'hover:bg-muted/50',
    'hover:text-accent-foreground',
    'hover:bg-destructive/30',
    'hover:bg-success/30',
    'hover:bg-warning/30',
    'hover:bg-info/30',
    'hover:bg-muted/80',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-ring',
    'focus:ring-ring/50',
    'focus:ring-offset-2',
    'focus:bg-accent',
    'focus:text-accent-foreground',
    'focus:bg-destructive/10',
    'focus:text-destructive',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-ring',
    'focus-visible:ring-offset-2',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
    'file:border-0',
    'file:bg-transparent',
    'file:text-sm',
    'file:font-medium',
    'placeholder:text-muted-foreground',
    'data-[disabled]:pointer-events-none',
    'data-[disabled]:opacity-50',
    'data-[state=selected]:bg-muted',
    'animate-in',
    'fade-in-80',
    'cursor-default',
    'select-none',
    'transform',
    'lg:translate-x-0',
    'inset-y-0',
    'left-0',
    'z-50',
    'w-64',
    'fixed',
    'whitespace-nowrap',
    'align-middle',
    'text-left',
    'uppercase',
    'text-xs',
    'overflow-x-auto',
    'bg-background',
    'text-foreground',
    'border-border',
  ],
  theme: {
    extend: {
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: '#ffffff',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: '#ffffff',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: '#ffffff',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
  corePlugins: {
    preflight: true,
  },
  theme: {
    extend: {
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
    },
  },
};
